version: '3'
services:
  app:
    build: .
    ports:
      - "0:3000"
    environment:
      - MONGO_URL=mongodb+srv://claraema7:Claraema1717@cluster0.lcypcnd.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"